version: "3"
services:
#  Create a service named db.
  db:
#   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
#   Give the container the name my_postgres. You can changes to something else.
    container_name: "labela_postgres"
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamob
      - DATABASE_HOST=postgres
#   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
#   Set a volume so that database is not lost after shutting down the container.
#   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  labela-app:
    build:
      context: .
    container_name: "labela_app"
    depends_on:
      - db
    ports:
      - 7654:7654
    command: bash -c "python setup.py develop && pserve development.ini --reload"
    volumes:
      - ./label_automobile:/app/label_automobile